Fix cs
codelicia/xulieta-json pull request #1
Opened 2020-11-12 21:33 UTC by ScullWM

2020-11-12 21:36 UTC, EHER approved these changes

2020-11-12 21:38 UTC, EHER commented
Thanks @ScullWM ! ❤️

Would be nice to have something on the project to check the code style.

2020-11-12 22:33 UTC, malukenho requested changes
`php-cs` is too loose on checking. We should use `doctrine/coding-standard` because it has several advantages, as for example, it denies undefined `array` type usage.

2020-11-13 16:53 UTC, szepeviktor commented
> `php-cs` is too loose on checking.

:) `doctrine/coding-standard` is a standard for PHPCS

`vendor/bin/phpcs --standard=Doctrine src/`

2020-11-13 16:55 UTC, szepeviktor commented
I see! After looking an the code: php-cs-fixer is really too loose.

2020-11-13 16:56 UTC, szepeviktor commented on .github/workflows/php.yml
> +      run: composer validate
```suggestion
      run: composer validate --strict
```

2020-11-13 17:28 UTC, malukenho approved these changes

2020-11-13 17:30 UTC, merged

2020-11-13 17:30 UTC, malukenho commented
I've made some changes to this PR:

- Use `doctrine/coding-standard`
- Rebase and Squased all commits
- Sign for participants
- Add validation `--strict` on composer as per @szepeviktor review

Thank you all! @ScullWM @szepeviktor 🎊

2020-11-25 16:28 UTC, malukenho commented
@all-contributors please add @ScullWM  for code